// web/src/views/ChatView.tsx
import { useState, useEffect } from 'react'
import SessionSidebar from '@/components/SessionSidebar'
import ChatPanel from '@/components/ChatPanel'
import MemoryPanel from '@/components/MemoryPanel'
import { cn } from '@/lib/utils'

export default function ChatView() {
  const [memoryWidth, setMemoryWidth] = useState(360)
  const [isDragging, setIsDragging] = useState(false)

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault()
    setIsDragging(true)
    const startX = e.clientX
    const startWidth = memoryWidth

    const handleMouseMove = (ev: MouseEvent) => {
      const delta = startX - ev.clientX
      setMemoryWidth(Math.max(240, Math.min(800, startWidth + delta)))
    }

    const handleMouseUp = () => {
      setIsDragging(false)
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
    }

    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseup', handleMouseUp)
  }

  useEffect(() => {
    return () => {
      setIsDragging(false)
    }
  }, [])

  return (
    <div className={cn('flex h-screen w-full', isDragging && 'cursor-col-resize select-none')}>
      <SessionSidebar />
      <ChatPanel />

      {/* Resize handle */}
      <div
        className={cn(
          'w-1.5 cursor-col-resize flex items-center justify-center flex-shrink-0 relative z-10 transition-colors hover:bg-primary/20',
          isDragging && 'bg-primary/20'
        )}
        onMouseDown={handleMouseDown}
      >
        <div
          className={cn(
            'w-0.5 h-8 rounded-full bg-border transition-all',
            'hover:bg-primary hover:h-12',
            isDragging && 'bg-primary h-12'
          )}
        />
      </div>

      <MemoryPanel style={{ width: `${memoryWidth}px`, minWidth: `${memoryWidth}px` }} />
    </div>
  )
}

// web/src/views/ChatView.vue
<script setup lang="ts">
import { ref } from 'vue'
import SessionSidebar from '../components/SessionSidebar.vue'
import ChatPanel from '../components/ChatPanel.vue'
import MemoryPanel from '../components/MemoryPanel.vue'

const memoryWidth = ref(360)
const isDragging = ref(false)

function onMouseDown(e: MouseEvent) {
  e.preventDefault()
  isDragging.value = true
  const startX = e.clientX
  const startWidth = memoryWidth.value

  function onMouseMove(ev: MouseEvent) {
    const delta = startX - ev.clientX
    memoryWidth.value = Math.max(240, Math.min(800, startWidth + delta))
  }
  function onMouseUp() {
    isDragging.value = false
    document.removeEventListener('mousemove', onMouseMove)
    document.removeEventListener('mouseup', onMouseUp)
  }
  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onMouseUp)
}
</script>

<template>
  <div :class="['chat-layout', { dragging: isDragging }]">
    <SessionSidebar />
    <ChatPanel />
    <div class="resize-handle" @mousedown="onMouseDown">
      <div class="resize-line" />
    </div>
    <MemoryPanel :style="{ width: memoryWidth + 'px', minWidth: memoryWidth + 'px' }" />
  </div>
</template>

<style scoped>
.chat-layout {
  display: flex;
  height: 100vh;
  width: 100%;
}

.chat-layout.dragging {
  cursor: col-resize;
  user-select: none;
}

.resize-handle {
  width: 6px;
  cursor: col-resize;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  position: relative;
  z-index: 10;
  transition: background 0.15s;
}

.resize-handle:hover,
.chat-layout.dragging .resize-handle {
  background: var(--accent-muted);
}

.resize-line {
  width: 2px;
  height: 32px;
  border-radius: 1px;
  background: var(--border-primary);
  transition: background 0.15s, height 0.15s;
}

.resize-handle:hover .resize-line,
.chat-layout.dragging .resize-line {
  background: var(--accent);
  height: 48px;
}
</style>
