// web/src/components/ApiMonitor.tsx
import { useState } from 'react'
import { useAppStore } from '@/store/app'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { ChevronDown, ChevronRight, Trash2 } from 'lucide-react'
import JsonViewer from './JsonViewer'
import { cn } from '@/lib/utils'

export default function ApiMonitor() {
  const { apiLogs, clearApiLogs } = useAppStore()
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set())

  const toggleExpand = (id: string) => {
    const newSet = new Set(expandedIds)
    if (newSet.has(id)) {
      newSet.delete(id)
    } else {
      newSet.add(id)
    }
    setExpandedIds(newSet)
  }

  const getMethodColor = (method: string) => {
    switch (method.toUpperCase()) {
      case 'GET':
        return 'bg-info/10 text-info'
      case 'POST':
        return 'bg-success/10 text-success'
      case 'DELETE':
        return 'bg-destructive/10 text-destructive'
      case 'PUT':
      case 'PATCH':
        return 'bg-warning/10 text-warning'
      default:
        return 'bg-muted text-muted-foreground'
    }
  }

  const getStatusColor = (status?: number) => {
    if (!status) return 'text-muted-foreground'
    if (status >= 200 && status < 300) return 'text-success'
    if (status >= 400 && status < 500) return 'text-warning'
    if (status >= 500) return 'text-destructive'
    return 'text-muted-foreground'
  }

  return (
    <Card className="p-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold">API Monitor</h3>
        <Button
          variant="ghost"
          size="sm"
          onClick={clearApiLogs}
          disabled={apiLogs.length === 0}
        >
          <Trash2 className="h-3 w-3 mr-1" />
          Clear
        </Button>
      </div>

      <ScrollArea className="h-[400px]">
        <div className="space-y-2">
          {apiLogs.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-8">
              No API requests yet
            </p>
          ) : (
            apiLogs.map((log) => {
              const isExpanded = expandedIds.has(log.id)
              return (
                <div
                  key={log.id}
                  className="border rounded-lg p-3 hover:bg-muted/50 transition-colors"
                >
                  <div
                    className="flex items-center gap-2 cursor-pointer"
                    onClick={() => toggleExpand(log.id)}
                  >
                    {isExpanded ? (
                      <ChevronDown className="h-3 w-3 text-muted-foreground flex-shrink-0" />
                    ) : (
                      <ChevronRight className="h-3 w-3 text-muted-foreground flex-shrink-0" />
                    )}
                    <Badge
                      variant="secondary"
                      className={cn('text-[10px] font-medium', getMethodColor(log.method))}
                    >
                      {log.method}
                    </Badge>
                    <span className="text-xs font-mono flex-1 truncate">{log.url}</span>
                    {log.status && (
                      <span className={cn('text-xs font-medium', getStatusColor(log.status))}>
                        {log.status}
                      </span>
                    )}
                    {log.duration !== undefined && (
                      <span className="text-xs text-muted-foreground">{log.duration}ms</span>
                    )}
                  </div>

                  {isExpanded && (
                    <div className="mt-3 space-y-2 pl-5">
                      {log.error && (
                        <div>
                          <p className="text-xs font-medium text-destructive mb-1">Error:</p>
                          <p className="text-xs text-destructive/80">{log.error}</p>
                        </div>
                      )}
                      {log.requestBody && (
                        <div>
                          <p className="text-xs font-medium mb-1">Request:</p>
                          <JsonViewer data={log.requestBody} maxHeight={200} />
                        </div>
                      )}
                      {log.responseBody && (
                        <div>
                          <p className="text-xs font-medium mb-1">Response:</p>
                          <JsonViewer data={log.responseBody} maxHeight={200} />
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )
            })
          )}
        </div>
      </ScrollArea>
    </Card>
  )
}

// web/src/components/ApiMonitor.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore } from '../stores/app'
import { Trash2 } from 'lucide-vue-next'

const app = useAppStore()

const recentLogs = computed(() => app.apiLogs.filter((l) => l.status !== undefined).slice(0, 20))

function statusClass(status?: number) {
  if (!status) return 'status-err'
  if (status < 300) return 'status-ok'
  if (status < 500) return 'status-warn'
  return 'status-err'
}

function methodClass(method: string) {
  const m = method.toUpperCase()
  if (m === 'POST') return 'method-post'
  if (m === 'DELETE') return 'method-delete'
  return 'method-get'
}
</script>

<template>
  <div class="api-monitor">
    <div class="monitor-header">
      <span class="monitor-title">API Monitor</span>
      <button class="btn btn-ghost btn-sm" @click="app.clearApiLogs">
        <Trash2 :size="14" />
      </button>
    </div>
    <div class="monitor-body">
      <div v-if="recentLogs.length === 0" class="empty-state">
        等待 API 请求…
      </div>
      <div v-for="log in recentLogs" :key="log.id" class="log-entry">
        <div class="log-header">
          <span :class="['log-method', methodClass(log.method)]">{{ log.method }}</span>
          <span class="log-url mono">{{ log.url }}</span>
          <span :class="['log-status', statusClass(log.status)]">{{ log.status }}</span>
          <span class="log-duration">{{ log.duration }}ms</span>
        </div>
        <details v-if="log.requestBody" class="log-detail">
          <summary>Request Body</summary>
          <pre class="log-json">{{ JSON.stringify(log.requestBody, null, 2) }}</pre>
        </details>
        <details v-if="log.responseBody" class="log-detail">
          <summary>Response</summary>
          <pre class="log-json">{{ JSON.stringify(log.responseBody, null, 2) }}</pre>
        </details>
      </div>
    </div>
  </div>
</template>

<style scoped>
.api-monitor {
  background: var(--bg-card);
  border: 1px solid var(--border-primary);
  border-radius: var(--radius-lg);
  overflow: hidden;
  display: flex;
  flex-direction: column;
  height: 100%;
}

.monitor-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border-primary);
}

.monitor-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.monitor-body {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.empty-state {
  padding: 40px 20px;
  text-align: center;
  color: var(--text-tertiary);
  font-size: 13px;
}

.log-entry {
  padding: 8px 10px;
  border-radius: var(--radius-sm);
  margin-bottom: 4px;
}

.log-entry:hover {
  background: var(--bg-hover);
}

.log-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.log-method {
  font-family: var(--font-mono);
  font-weight: 600;
  font-size: 11px;
  padding: 1px 6px;
  border-radius: 3px;
  min-width: 50px;
  text-align: center;
}

.method-get { background: var(--info-muted); color: var(--info); }
.method-post { background: var(--success-muted); color: var(--success); }
.method-delete { background: var(--error-muted); color: var(--error); }

.log-url {
  flex: 1;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.log-status {
  font-family: var(--font-mono);
  font-weight: 600;
  font-size: 11px;
}

.status-ok { color: var(--success); }
.status-warn { color: var(--warning); }
.status-err { color: var(--error); }

.log-duration {
  color: var(--text-tertiary);
  font-size: 11px;
  font-family: var(--font-mono);
  min-width: 50px;
  text-align: right;
}

.log-detail {
  margin-top: 6px;
}

.log-detail summary {
  font-size: 11px;
  color: var(--text-tertiary);
  cursor: pointer;
  user-select: none;
}

.log-json {
  margin-top: 4px;
  background: var(--bg-primary);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-sm);
  padding: 8px 10px;
  font-family: var(--font-mono);
  font-size: 11px;
  line-height: 1.6;
  color: var(--accent);
  overflow-x: auto;
  max-height: 200px;
  white-space: pre-wrap;
  word-break: break-all;
}
</style>
